<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from "$lib/components/qwer/layouts/post.svelte";
  import ImgZoom from "$lib/components/qwer/components/image_zoom.svelte";
  import Video from "$lib/components/qwer/components/video.svelte";
  import CodeCopy from "$lib/components/qwer/components/code_copy.svelte";
  import InfoBox from "$lib/components/qwer/components/info_box.svelte";

  /*<!-- :QWER IMPORTS: -->*/
</script>

<Post>
  <article slot="post_content">
    <!-- :QWER CONTENT: -->
  </article>
</Post>
